version: '3'
services:
  sfm:
    image: tianlechen/sfm:latest
    environment:
      - CONFIG_DIR=/config
    volumes:
      - ./config:/config
      - ./testdir:/watchdir
    ports:
      - 8501:8501
